import { TAU, wrapAngle, angularDistance, scoreForShard, scoreForEchoAction, orbitSpeedMultiplier, difficultyAt, daySeed, mulberry32 } from './logic.js';

const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);
const ui={home:$('home'),tutorial:$('tutorial'),over:$('gameover'),vault:$('vaultScreen'),hud:$('hud'),score:$('score'),best:$('best'),combo:$('combo'),toast:$('toast'),mission:$('missionChip'),bossBar:$('bossBar'),bossHealth:$('bossHealth')};
const PLANETS=[
  {id:'luma',name:'LUMA',color:'#75f5ff',cost:0,mult:1,pressure:1,desc:'★ 안정적인 원형 중력'},
  {id:'vela',name:'VELA',color:'#ffd85c',cost:40,mult:1.1,pressure:.95,desc:'★★ 근일점 가속 · ×1.1'},
  {id:'nox',name:'NOX',color:'#b48aff',cost:120,mult:1.25,pressure:.9,desc:'★★★ 교차점 가속 · ×1.25'},
  {id:'kairos',name:'KAIROS',color:'#ff7cb7',cost:220,mult:1.4,pressure:.82,desc:'★★★★ 삼중 가속 · ×1.4'},
  {id:'rift',name:'RIFT',color:'#75ffb2',cost:400,mult:1.6,pressure:.75,desc:'★★★★★ 코너 폭주 · ×1.6'},
  {id:'abyss',name:'ABYSS',color:'#ff735c',cost:700,mult:2,pressure:.68,desc:'★★★★★★ 다중 교차 · ×2'},
];
const MISSION_POOL=[{type:'collect',target:8,text:n=>`빛 ${n}/8`},{type:'near',target:3,text:n=>`스침 ${n}/3`},{type:'combo',target:5,text:n=>`콤보 ×${n}/5`},{type:'survive',target:25,text:n=>`생존 ${n}/25초`}];
let width=0,height=0,dpr=1,cx=0,cy=0,orbit=130,state='home',last=0,elapsed=0,spawnClock=0,shake=0,flash=0,daily=false;
let player,hazards=[],shards=[],particles=[],stars=[],boss=null,bossTriggered=false,missions=[],history=[],echoes=[];
let score=0,best=Number(localStorage.getItem('luma-best')||0),combo=1,collected=0,nearMisses=0,maxCombo=1,totalLight=Number(localStorage.getItem('luma-light')||0);
let selectedPlanet=localStorage.getItem('luma-planet')||'luma',echoEquipped=localStorage.getItem('luma-echo')==='1',muted=localStorage.getItem('luma-muted')==='1',audio,random=Math.random,echoMode=false,tutorialFromHelp=false;

function resize(){dpr=Math.min(devicePixelRatio||1,2);width=innerWidth;height=innerHeight;canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);cx=width/2;cy=height*.52;orbit=Math.min(width*.31,height*.205,155);stars=Array.from({length:Math.floor(width*height/8500)},()=>({x:Math.random()*width,y:Math.random()*height,r:Math.random()*1.2,a:.12+Math.random()*.35}));}
addEventListener('resize',resize);resize();ui.best.textContent=best;
const dailyKey=`luma-daily-${daySeed()}`;$('sound').textContent=muted?'×':'♪';$('vaultStatus').textContent=`${planet().name}${echoEquipped?' · ECHO':''}`;
function tone(freq=440,duration=.08,type='sine',volume=.05){if(muted)return;audio||=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function chord(notes){notes.forEach((note,i)=>setTimeout(()=>tone(note,.16,'triangle',.045),i*65));}
function vibrate(pattern){if(navigator.vibrate)navigator.vibrate(pattern);}
function screen(id){[ui.home,ui.tutorial,ui.over,ui.vault].forEach(x=>{x.classList.remove('active');x.setAttribute('aria-hidden','true')});if(id){id.classList.add('active');id.setAttribute('aria-hidden','false');}}
function showToast(text,duration=650){ui.toast.textContent=text;ui.toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>ui.toast.classList.remove('show'),duration);}
function planet(){return PLANETS.find(item=>item.id===selectedPlanet)||PLANETS[0];}
function scoreMultiplier(){return planet().mult;}
function point(angle,r=orbit){const scale=r/orbit,c=Math.cos(angle),s=Math.sin(angle);if(selectedPlanet==='vela')return{x:cx+c*orbit*1.14*scale,y:cy+s*orbit*.72*scale};if(selectedPlanet==='nox')return{x:cx+Math.sin(angle)*orbit*scale,y:cy+Math.sin(angle*2)*orbit*.52*scale};if(selectedPlanet==='kairos'){const radius=orbit*(.72+.28*Math.cos(angle*3))*scale;return{x:cx+c*radius,y:cy+s*radius};}if(selectedPlanet==='rift')return{x:cx+Math.sign(c)*Math.pow(Math.abs(c),.46)*orbit*scale,y:cy+Math.sign(s)*Math.pow(Math.abs(s),.46)*orbit*.82*scale};if(selectedPlanet==='abyss')return{x:cx+Math.sin(angle*2)*orbit*.96*scale,y:cy+Math.sin(angle*3)*orbit*.68*scale};return{x:cx+c*r,y:cy+s*r};}
function gravitySpeed(angle){return orbitSpeedMultiplier(selectedPlanet,angle);}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function segmentDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,length=dx*dx+dy*dy;if(!length)return distance(p,a);const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/length));return distance(p,{x:a.x+t*dx,y:a.y+t*dy});}
function chooseMissions(){const pool=[...MISSION_POOL].sort(()=>random()-.5);missions=pool.slice(0,3).map(item=>({...item,progress:0,done:false}));updateMissions();}
function updateMissions(){for(const m of missions){m.progress=m.type==='collect'?collected:m.type==='near'?nearMisses:m.type==='combo'?maxCombo:Math.floor(elapsed);if(!m.done&&m.progress>=m.target){m.done=true;score+=100;showToast('MISSION COMPLETE  +100',1100);chord([520,660,820]);}}const active=missions.find(m=>!m.done)||missions[missions.length-1];ui.mission.textContent=active?(active.done?'ALL MISSIONS COMPLETE':active.text(Math.min(active.progress,active.target))):'';}
function begin(isDaily=false,useEcho=echoEquipped){daily=isDaily;echoMode=useEcho;random=daily?mulberry32(daySeed()):Math.random;state='playing';elapsed=0;spawnClock=.7;score=0;combo=1;collected=0;nearMisses=0;maxCombo=1;hazards=[];shards=[];particles=[];history=[];echoes=[];boss=null;bossTriggered=false;player={angle:-Math.PI/2,dir:1,speed:1.65};chooseMissions();screen(null);ui.hud.classList.remove('hidden');ui.bossBar.classList.remove('active');updateHud();tone(330,.12,'sine',.07);showToast(`${planet().name}${echoMode?' · ECHO':''}  ×${scoreMultiplier()}`,900);if(echoMode)setTimeout(()=>showToast('SPLIT · CUT · REUNITE',1400),950);}
function flip(){if(state!=='playing')return;if(echoMode){echoes.push({angle:player.angle,dir:player.dir,age:0,duration:6,spent:false});echoes=echoes.slice(-3);showToast('TIMELINE SPLIT',550);tone(390,.14,'sine',.035);}player.dir*=-1;burst(point(player.angle),planet().color,9);tone(520,.045,'triangle',.035);vibrate(8);}
function spawn(){const a=random()*TAU;hazards.push({angle:a,age:0,life:3.6,near:false});const offset=(random()>.5?1:-1)*(.58+random()*.38);shards.push({angle:wrapAngle(a+offset),age:0,life:4.1,pulse:random()*TAU,boss:false});}
function spawnBossWave(){const base=random()*TAU;for(let i=0;i<3;i++)hazards.push({angle:wrapAngle(base+i*TAU/3),age:0,life:3.1,near:false,boss:true});shards.push({angle:wrapAngle(base+Math.PI/3),age:0,life:3.5,pulse:0,boss:true});}
function startBoss(){bossTriggered=true;boss={hp:4,maxHp:4,clock:.3,angle:0};hazards=[];shards=[];ui.bossBar.classList.add('active');showToast('⚠  THE ECLIPSE  ⚠',1600);shake=8;flash=.6;vibrate([30,30,30]);tone(82,.7,'sawtooth',.08);}
function defeatBoss(){score+=500;boss=null;hazards=[];shards=[];ui.bossBar.classList.remove('active');showToast('ECLIPSE SHATTERED  +500',1500);shake=18;flash=1;chord([330,440,660,880]);vibrate([25,25,25,25,80]);for(let i=0;i<8;i++)burst(point(i*TAU/8,orbit*.55),'#ffd85c',12);}
function burst(p,color,count=12){for(let i=0;i<count;i++){const a=Math.random()*TAU,s=25+Math.random()*115;particles.push({x:p.x,y:p.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.35,max:.7,color});}}
function updateHud(){ui.score.textContent=Math.floor(score);ui.best.textContent=Math.max(best,Math.floor(score));ui.combo.textContent=`×${combo}`;ui.combo.classList.toggle('hot',combo>1);if(boss)ui.bossHealth.style.width=`${boss.hp/boss.maxHp*100}%`;}
function paradox(e){e.dead=true;const cleared=hazards.filter(h=>h.age>.55&&h.age<2.2),gain=scoreForEchoAction('paradox',cleared.length);cleared.forEach(h=>{h.dead=true;burst(point(h.angle),'#d8c5ff',15);});score+=gain;combo=Math.min(9,combo+1);maxCombo=Math.max(maxCombo,combo);if(boss){boss.hp--;if(boss.hp<=0)defeatBoss();}burst(point(player.angle),'#ffffff',42);shake=20;flash=1;showToast(`PARADOX  +${gain}`,1200);chord([220,440,660,990]);vibrate([20,20,80]);}
function update(dt){if(state!=='playing')return;elapsed+=dt;const diff=difficultyAt(elapsed);player.angle=wrapAngle(player.angle+player.dir*player.speed*diff.speed*gravitySpeed(player.angle)*dt);for(const e of echoes){e.age+=dt;e.angle=wrapAngle(e.angle+e.dir*player.speed*diff.speed*gravitySpeed(e.angle)*dt);if(e.age>.65&&distance(point(e.angle),point(player.angle))<13)paradox(e);}echoes=echoes.filter(e=>e.age<e.duration&&!e.dead);score+=dt*(2+combo*.35)*scoreMultiplier();if(!bossTriggered&&elapsed>=30)startBoss();if(boss){boss.angle+=dt*.7;boss.clock-=dt;if(boss.clock<=0){spawnBossWave();boss.clock=1.7*planet().pressure;}}else{spawnClock-=dt;if(spawnClock<=0){spawn();spawnClock=diff.spawnEvery*(.82+random()*.35)*planet().pressure;}}
  hazards.forEach(h=>{h.age+=dt;const active=h.age>.7&&h.age<2,hp=point(h.angle),pp=point(player.angle),echo=echoes.find(e=>distance(point(e.angle),hp)<13),cut=echoMode&&echoes.some(e=>e.age>.15&&segmentDistance(hp,pp,point(e.angle))<7);if(active&&(echo||cut)){const action=cut?'cut':'hit',gain=scoreForEchoAction(action);h.dead=true;score+=gain;burst(hp,cut?'#ffffff':'#b48aff',24);showToast(`${cut?'GRAVITY CUT':'ECHO HIT'}  +${gain}`,700);shake=6;}else if(active&&distance(pp,hp)<13)endGame();else if(active&&!h.near&&distance(pp,hp)<32){h.near=true;nearMisses++;score+=15*combo;combo=Math.min(9,combo+1);maxCombo=Math.max(maxCombo,combo);showToast(`NEAR MISS  +${15*(combo-1)}`);tone(760,.08,'sine',.045);vibrate(12);shake=Math.max(shake,3);}});
  shards.forEach(s=>{s.age+=dt;s.pulse+=dt*4;const sp=point(s.angle),echo=echoes.find(e=>distance(point(e.angle),sp)<15),playerHit=distance(point(player.angle),sp)<15;if(s.age>.25&&s.age<s.life&&(echo||playerHit)){const echoHarvest=echo&&!playerHit;s.dead=true;collected++;const gain=Math.round(scoreForShard(combo)*scoreMultiplier());score+=gain;if(!echoHarvest){combo=Math.min(9,combo+1);maxCombo=Math.max(maxCombo,combo);}burst(sp,s.boss?'#ffd85c':planet().color,18);tone(s.boss?900:620+combo*45,.1,'triangle',.055);shake=Math.max(shake,s.boss?7:2);if(s.boss&&boss){boss.hp--;if(boss.hp<=0)defeatBoss();}else showToast(`${echoHarvest?'ECHO HARVEST':'LIGHT'}  +${gain}`);}});
  hazards=hazards.filter(h=>h.age<h.life&&!h.dead);shards=shards.filter(s=>s.age<s.life&&!s.dead);particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.98;p.vy*=.98});particles=particles.filter(p=>p.life>0);shake=Math.max(0,shake-dt*30);flash=Math.max(0,flash-dt*3);updateMissions();updateHud();}
function saveScore(value){const board=JSON.parse(localStorage.getItem('luma-board')||'[]');board.push({score:value,date:new Date().toISOString().slice(0,10)});board.sort((a,b)=>b.score-a.score);localStorage.setItem('luma-board',JSON.stringify(board.slice(0,5)));}
function endGame(){if(state!=='playing')return;state='over';shake=18;flash=1;burst(point(player.angle),'#ff5c98',35);tone(110,.35,'sawtooth',.07);vibrate([35,35,70]);const final=Math.floor(score),oldLight=totalLight;best=Math.max(best,final);totalLight+=collected;localStorage.setItem('luma-best',best);localStorage.setItem('luma-light',totalLight);saveScore(final);if(daily)localStorage.setItem(dailyKey,Math.max(Number(localStorage.getItem(dailyKey)||0),final));const unlocked=PLANETS.find(s=>s.cost>oldLight&&s.cost<=totalLight);if(unlocked)setTimeout(()=>showToast(`${unlocked.name} PLANET UNLOCKED`,1600),900);setTimeout(()=>{ui.hud.classList.add('hidden');ui.bossBar.classList.remove('active');$('finalScore').textContent=final;$('finalBest').textContent=best;$('shards').textContent=collected;$('nearMisses').textContent=nearMisses;$('maxCombo').textContent='×'+maxCombo;$('resultLabel').textContent=daily?'DAILY ORBIT COMPLETE':echoMode?'TIMELINE COLLAPSED':'ORBIT LOST';const done=missions.filter(m=>m.done).length;$('missionResult').innerHTML=`${planet().name} · 미션 ${done}/3 ${done?`· <b>+${done*100}</b>`:''}`;screen(ui.over);},650);}

function drawBackground(t){const g=ctx.createRadialGradient(cx,cy,0,cx,cy,Math.max(width,height)*.65);g.addColorStop(0,flash?`rgba(255,60,120,${.14*flash})`:'#172044');g.addColorStop(.45,'#0b1025');g.addColorStop(1,'#050711');ctx.fillStyle=g;ctx.fillRect(0,0,width,height);for(const s of stars){ctx.globalAlpha=s.a*(.75+.25*Math.sin(t*.001+s.x));ctx.fillStyle='#c8eaff';ctx.fillRect(s.x,s.y,s.r,s.r);}ctx.globalAlpha=1;}
function drawTrack(){ctx.beginPath();for(let i=0;i<=160;i++){const p=point(i/160*TAU);if(i)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y);}ctx.closePath();ctx.strokeStyle=planet().color+'32';ctx.lineWidth=1.2;ctx.stroke();}
function drawOrbit(t){ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawTrack();const core=ctx.createRadialGradient(cx,cy,0,cx,cy,boss?58:40);core.addColorStop(0,boss?'#ffdda1':'#fff');core.addColorStop(.14,boss?'#ff668e':planet().color);core.addColorStop(.42,boss?'#871d55aa':planet().color+'66');core.addColorStop(1,'#7489ff00');ctx.fillStyle=core;ctx.beginPath();ctx.arc(cx,cy,boss?58:40,0,TAU);ctx.fill();ctx.beginPath();ctx.arc(cx,cy,13,0,TAU);ctx.fillStyle=boss?'#ff9aae':planet().color;ctx.globalAlpha=.55;ctx.fill();ctx.globalAlpha=1;if(boss){ctx.save();ctx.translate(cx,cy);ctx.rotate(boss.angle);for(let i=0;i<6;i++){ctx.rotate(TAU/6);ctx.fillStyle='#ff6b9d55';ctx.fillRect(35,-1,30,2);}ctx.restore();}
  for(const h of hazards){const phase=h.age<.7?h.age/.7:h.age<2?1:Math.max(0,1-(h.age-2)/1.1),p=point(h.angle);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(h.angle+Math.PI/2);ctx.globalAlpha=phase;ctx.shadowBlur=h.boss?30:20;ctx.shadowColor='#ff477f';ctx.fillStyle='#ff5c8c';ctx.fillRect(h.boss?-4:-3,h.boss?-27:-19,h.boss?8:6,h.boss?54:38);ctx.fillStyle='#fff';ctx.fillRect(-1,h.boss?-18:-12,2,h.boss?36:24);ctx.restore();if(h.age<.7){ctx.beginPath();ctx.arc(p.x,p.y,8+h.age*34,0,TAU);ctx.strokeStyle=`rgba(255,90,140,${.45-h.age*.55})`;ctx.stroke();}}
  for(const s of shards){const phase=Math.min(1,s.age*4)*Math.min(1,(s.life-s.age)*2),p=point(s.angle);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(s.pulse);ctx.globalAlpha=phase;ctx.shadowBlur=s.boss?28:17;ctx.shadowColor=s.boss?'#ffd85c':'#a58aff';ctx.fillStyle=s.boss?'#fff2a3':'#d7caff';const size=s.boss?10:7;ctx.beginPath();ctx.moveTo(0,-size);ctx.lineTo(size*.7,0);ctx.lineTo(0,size);ctx.lineTo(-size*.7,0);ctx.closePath();ctx.fill();ctx.restore();}
  if(echoMode&&player){const pp=point(player.angle);for(const e of echoes){const p=point(e.angle),alpha=Math.min(.8,(1-e.age/e.duration)*1.4);const beam=ctx.createLinearGradient(pp.x,pp.y,p.x,p.y);beam.addColorStop(0,planet().color+'18');beam.addColorStop(.5,'#ffffffbb');beam.addColorStop(1,'#b48aff33');ctx.globalAlpha=alpha;ctx.strokeStyle=beam;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(pp.x,pp.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.shadowBlur=25;ctx.shadowColor='#b48aff';ctx.fillStyle='#cbb8ff';ctx.beginPath();ctx.arc(p.x,p.y,7,0,TAU);ctx.fill();}}ctx.globalAlpha=1;
  if(player&&state!=='home'){const p=point(player.angle),color=planet().color;ctx.shadowBlur=25;ctx.shadowColor=color;ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,7,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.beginPath();ctx.arc(p.x,p.y,13+Math.sin(t*.006)*2,0,TAU);ctx.strokeStyle=color+'66';ctx.stroke();}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,2,2);}ctx.globalAlpha=1;ctx.restore();}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);drawBackground(t);if(state!=='home')drawOrbit(t);requestAnimationFrame(loop);}requestAnimationFrame(loop);
function openVault(){state='vault';$('totalLight').textContent=totalLight;$('vaultStatus').textContent=`${planet().name}${echoEquipped?' · ECHO':''}`;$('skins').innerHTML=PLANETS.map(s=>`<button class="skin ${s.id===selectedPlanet?'selected':''} ${totalLight<s.cost?'locked':''}" data-planet="${s.id}" style="--skin:${s.color}"><i></i><span>${totalLight>=s.cost?s.name:`${s.cost} 빛`}</span><small>${s.desc}</small></button>`).join('');document.querySelectorAll('.skin').forEach(button=>button.onclick=()=>{const item=PLANETS.find(s=>s.id===button.dataset.planet);if(totalLight<item.cost){showToast(`${item.cost-totalLight} LIGHT MORE`);return;}selectedPlanet=item.id;localStorage.setItem('luma-planet',selectedPlanet);openVault();tone(660,.12,'triangle',.05);});const toggle=$('echoToggle');toggle.classList.toggle('active',echoEquipped);$('echoState').textContent=echoEquipped?'ON':'OFF';toggle.onclick=()=>{echoEquipped=!echoEquipped;localStorage.setItem('luma-echo',echoEquipped?'1':'0');tone(echoEquipped?660:330,.12,'triangle',.05);openVault();};const board=JSON.parse(localStorage.getItem('luma-board')||'[]');$('leaderboard').innerHTML=board.length?board.map((item,i)=>`<li>#${i+1} · ${item.date}<b>${item.score}</b></li>`).join(''):'<li>첫 번째 전설이 되어보세요.<b>—</b></li>';screen(ui.vault);}
$('play').onclick=()=>{if(localStorage.getItem('luma-seen'))begin();else{tutorialFromHelp=false;screen(ui.tutorial);}};$('tutorialPlay').onclick=()=>{localStorage.setItem('luma-seen','1');if(tutorialFromHelp){state='home';screen(ui.home);}else begin();};$('info').onclick=()=>{tutorialFromHelp=true;screen(ui.tutorial);};$('retry').onclick=()=>begin(daily,echoMode);$('homeButton').onclick=()=>{state='home';screen(ui.home)};$('vault').onclick=openVault;$('closeVault').onclick=()=>{state='home';$('vaultStatus').textContent=`${planet().name}${echoEquipped?' · ECHO':''}`;screen(ui.home)};$('sound').onclick=()=>{muted=!muted;localStorage.setItem('luma-muted',muted?'1':'0');$('sound').textContent=muted?'×':'♪';if(!muted)tone(440);};canvas.addEventListener('pointerdown',e=>{e.preventDefault();flip();});addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();if(state==='playing')flip();else if(state==='home')$('play').click();else if(state==='over')$('retry').click();}});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
